services:
  # BANCO DE DADOS
  db:
    container_name: canteiro-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: acompanhamento_obras_db
    ports:
      - "5432:5432"
    networks:
      - app-net

  # BACKEND
  backend:
    container_name: canteiro-backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      # Rodando localmente vale a definição de .env
      #- DATABASE_URL=postgresql+psycopg2://postgres:postgres_password@localhost:5432/acompanhamento_obras_db
      # No Docker a conexão agora usa o nome do serviço "db" (sobrescreve a definição em .env)
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres_password@db:5432/acompanhamento_obras_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
    # Sobrescreve o CMD do Dockerfile para modo reload local
    command: flask run --host=0.0.0.0 --port=5000 --reload
    networks:
      - app-net

  # FRONTEND (Vite)
  frontend:
    container_name: canteiro-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Vai parar no primeiro estágio do Dockerfile (desenvolvimento)
      target: dev-stage    
    volumes:
      - ./frontend:/app     # Sincroniza código local com o container
      - /app/node_modules   # Evita que o node_modules local sobrescreva o do container
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    # Comando para rodar o Vite em modo desenvolvimento com Hot Reload
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge